"use client";
import localFont from "next/font/local";
import "./globals.css";
// import { PersistGate } from "redux-persist/integration/react";
import Header from "@/app/_components/header";
import { Provider } from "react-redux";
import { store } from "./_redux/store";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <Provider store={store}>{children}</Provider>
      </body>
    </html>
  );
}
